#include "Ex1.h"




void Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013A5 begin
{
    
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013A5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013A7 begin
{
    return 0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013A7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::newOperation(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:0000000000001377 begin
{
    
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:0000000000001377 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:000000000000137A begin
{
    
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:000000000000137A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:000000000000137D begin
{
    
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:000000000000137D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
