#include "FormesGeometriques.h"







double FormesGeometriques::TriangleRectancle::CalculerSurface(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013BE begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013BE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::TriangleRectancle::newOperation(double base, double hauter)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013C2 begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013C2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element






double FormesGeometriques::Rectangle::CalculerSurface(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013C8 begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013C8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::Rectangle::CalculePerimetre(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013CC begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013CC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element






double FormesGeometriques::Cercle::CalculeSurface(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013D4 begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013D4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::Cercle::CalculePerimetre(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013D8 begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013D8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element



double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013AC begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013AC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::newOperation(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013B0 begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013B0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013B4 begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013B4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013B6 begin
{
    return 0.0;
}
// section 10--28--98-88--2920f3c2:19a9af2b576:-8000:00000000000013B6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
